name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ ninja-build && sudo apt-get install -y cppcheck

    - name: Code formatting check
      run: |
        set +e
        clang-format -n --Werror src/*.cpp 
        if [ $? -ne 0 ]; then
        echo "Formatting issues detected:"
        clang-format -i src/*.cpp 
        git --no-pager diff
        exit 1
        fi


    - name: Static analysis (clang-tidy)
      run: clang-tidy src/*.cpp -- -std=c++17

    - name: Static analysis (cppcheck)
      run: cppcheck --enable=all --error-exitcode=1 src/


    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Build project
      run: ./build.sh

    - name: Run executable
      run: ./run.sh