name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ ninja-build

    - name: Code formatting check
      run: clang-format --dry-run --Werror src/*.cpp include/*.hpp

    - name: Static analysis (clang-tidy)
      run: clang-tidy src/*.cpp -- -std=c++17

    - name: Static analysis (cppcheck)
      run: cppcheck --enable=all --error-exitcode=1 src/


    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Build project
      run: ./build.sh

    - name: Run executable
      run: ./run.sh